default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  port: 5432

development:
  <<: *default
  database: precifikapp_devs
  username: postgres
  password: h4rdc0r3

test:
  <<: *default
  database: precifikapp_tests
  username: postgres
  password: h4rdc0r3

production:
  <<: *default
  database: precifikapp_prods
  username: postgres
  password: <%= ENV['PRODUCT_PRICING_APP_DATABASE_PASSWORD'] %>